# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1018, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.displaySensorDataMessage = QtWidgets.QTextEdit(self.centralwidget)
        self.displaySensorDataMessage.setGeometry(QtCore.QRect(630, 50, 311, 141))
        self.displaySensorDataMessage.setObjectName("displaySensorDataMessage")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(90, 40, 518, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.parkingLot1 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.parkingLot1.setObjectName("parkingLot1")
        self.horizontalLayout.addWidget(self.parkingLot1, 0, QtCore.Qt.AlignHCenter)
        self.parkingLot2 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.parkingLot2.setObjectName("parkingLot2")
        self.horizontalLayout.addWidget(self.parkingLot2, 0, QtCore.Qt.AlignHCenter)
        self.parkingLot3 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.parkingLot3.setObjectName("parkingLot3")
        self.horizontalLayout.addWidget(self.parkingLot3, 0, QtCore.Qt.AlignHCenter)
        self.parkingLot4 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.parkingLot4.setObjectName("parkingLot4")
        self.horizontalLayout.addWidget(self.parkingLot4, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.parkingLot5 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.parkingLot5.setObjectName("parkingLot5")
        self.horizontalLayout.addWidget(self.parkingLot5, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(110, 210, 160, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.warnOnButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.warnOnButton.setObjectName("warnOnButton")
        self.verticalLayout.addWidget(self.warnOnButton, 0, QtCore.Qt.AlignVCenter)
        self.warnOffButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.warnOffButton.setObjectName("warnOffButton")
        self.verticalLayout.addWidget(self.warnOffButton)
        self.message_to_displace = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.message_to_displace.setGeometry(QtCore.QRect(520, 240, 231, 91))
        self.message_to_displace.setObjectName("message_to_displace")
        self.messageButton = QtWidgets.QPushButton(self.centralwidget)
        self.messageButton.setGeometry(QtCore.QRect(650, 340, 100, 36))
        self.messageButton.setObjectName("messageButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1018, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.parkingLot1.setText(_translate("MainWindow", "1"))
        self.parkingLot2.setText(_translate("MainWindow", "2"))
        self.parkingLot3.setText(_translate("MainWindow", "3"))
        self.parkingLot4.setText(_translate("MainWindow", "4"))
        self.parkingLot5.setText(_translate("MainWindow", "5"))
        self.warnOnButton.setText(_translate("MainWindow", "Warn On"))
        self.warnOffButton.setText(_translate("MainWindow", "Warn Off"))
        self.message_to_displace.setPlainText(_translate("MainWindow", "\n"
""))
        self.messageButton.setText(_translate("MainWindow", "send"))
